encrypt-type: # 0:standard, 1:guomi
 encrypt-type: 0 
 
group-channel-connections-config:
  all-channel-connections:
  - group-id: 1  #group ID
    connections-str:
                    - ali.theproudsoul.cn:20200  # node listen_ip:channel_listen_port
                    - ali.theproudsoul.cn:20201
  - group-id: 2  
    connections-str:
                    - 127.0.0.1:20202  # node listen_ip:channel_listen_port
                    - 127.0.0.1:20203
 
channel-service:
  group-id: 1 # The specified group to which the SDK connects
  agency-name: fisco # agency name

#user-key:
#  user-key: 3bed914595c159cbce70ec5fb6aff3d6797e0c5ee5a7a9224a21cae8932d84a4

contract-address:
  account: 7506f526e04f33f00ac6eedc7b6935786d9caf9c
  pet-market: 946982993e0eb4b6cebfc1d5ba5d7375a7e824f0
  transaction: 197d9ec34f74db5dbc9d45a144da858d76497484

spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/test
    username: root
    password: zyj971213
    driver-class-name: org.mariadb.jdbc.Driver
    database-platform: org.hibernate.dialect.H2Dialect
    type-aliases-package: cn.theproudsoul.fiscopetstop.repository
    initialization-mode: always
    sql-script-encoding: utf-8

  h2:
    console:
      enabled: true # Enabling H2 Console
      path: /h2-console # Custom H2 Console URL

  jpa:
    hibernate:
      ddl-auto: none